openapi: 3.0.3
info:
  title: Web IDE
  description: Web IDE
  version: 1.0.0
servers:
  - url: 'http://localhost:8080/api'
paths:
  /v1/file:
    put:
      summary: 파일 수정
      description: 코드 에디터에 작성된 코드 수정
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                content:
                  type: string
                  description: Base64URL로 인코딩 된 파일 내용
                ext:
                  type: string
                  description: 파일 확장자
                name:
                  type: string
                  description: 파일 이름
      responses:
        '200':
          description: 파일 수정 성공
  '/v1/file/{id}/run':
    get:
      summary: 파일 실행
      description: 서버에 저장되어 있는 파일 실행
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: 파일 아이디
      responses:
        '200':
          description: 파일 실행 결과
          content:
            application/json:
              schema:
                type: object
                properties:
                  result:
                    type: string
                    description: 실행 결과
  '/v1/file/{id}':
    get:
      summary: 파일 불러오기
      description: 파일 아이디로 파일 불러오기
      parameters:
        - in: path
          name: id
          schema:
            type: integer
          required: true
          description: 파일 아이디
      responses:
        '200':
          description: 파일 불러오기 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: string
                    description: Base64URL로 인코딩 된 파일 내용
                  ext:
                    type: string
                    description: 파일 확장자
                  name:
                    type: string
                    description: 파일 이름
  /v1/auth/signin:
    post:
      summary: 로그인
      description: 이메일과 비밀번호로 로그인
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 이메일
                password:
                  type: string
                  description: 비밀번호
      responses:
        '200':
          description: 로그인 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  access-token:
                    type: string
                    description: 인증 토큰
        '401':
          description: 로그인 실패
  /v1/auth/signup:
    post:
      summary: 회원가입
      description: '이메일, 비밀번호로 회원가입'
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                email:
                  type: string
                  description: 이메일
                password:
                  type: string
                  description: 비밀번호
      responses:
        '200':
          description: 회원가입 성공
          content:
            application/json:
              schema:
                type: object
                properties:
                  access-token:
                    type: string
                    description: 인증 토큰
        '401':
          description: 회원가입 실패


